trigger:
  branches:
    include:
      - main
pool:
  name: Default
stages:

- stage: CI
  jobs:
    - job: Terraform
      variables:
        - group: my-secrets
      steps:
        - checkout: self

        - script: |
             echo "Installing AWS CLI..."
             curl "https://d1wni0z0v2x3q4.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
             aws sts get-caller-identity
          displayName: 'Install AWS CLI'
          env:
            AWS_ACCESS_KEY_ID: $(aws_access_key_id)
            AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
            AWS_SESSION_TOKEN: $(aws_session_token)

        - script: |
             echo "Checking AWS credentials..."
             echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
             echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
             echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
          displayName: 'Check AWS Credentials'
          condition: succeeded()

        - script: |
             echo "Checking AWS CLI version..."
             aws sts get-caller-identity
          displayName: 'Check AWS CLI Version'
          condition: succeeded()

        - script: terraform fmt
          displayName: 'Terraform Format'
          condition: succeeded()

        - script: terraform init
          displayName: 'Terraform Init'
          condition: succeeded()

        - script: terraform plan -out=tfplan
          displayName: 'Terraform Plan'
          condition: succeeded()

        - script: terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'
          condition: succeeded()
    - job: k8s
      condition: succeeded('Terraform')
      steps:
        - checkout: self
        - script: |
            aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
          displayName: 'Update kubeconfig'
          
        - script: |
            kubectl get nodes -A
          displayName: 'Check nodes'
          condition: succeeded()
